// Generated by scripts/bundle-api.mjs from server/handlers. Do not edit by hand.

// src/lib/markets/polymarket.ts
var GAMMA_SEARCH = "https://gamma-api.polymarket.com/public-search";
var GAMMA_EVENTS = "https://gamma-api.polymarket.com/events";
var EVENT_URL = "https://polymarket.com/event";
var MAX_MATCHES = 3;
var MAX_TRENDS = 4;
var USER_AGENT = "WeAlmostAgree/0.1 (educational market lens; +https://www.wealmostagree.com)";
var STOP = /* @__PURE__ */ new Set([
  "a",
  "an",
  "the",
  "is",
  "are",
  "was",
  "were",
  "be",
  "been",
  "being",
  "am",
  "to",
  "of",
  "in",
  "on",
  "for",
  "and",
  "or",
  "but",
  "if",
  "that",
  "this",
  "these",
  "those",
  "it",
  "its",
  "my",
  "your",
  "our",
  "their",
  "we",
  "you",
  "they",
  "i",
  "he",
  "she",
  "will",
  "would",
  "should",
  "could",
  "can",
  "may",
  "might",
  "must",
  "shall",
  "just",
  "really",
  "very",
  "so",
  "than",
  "then",
  "with",
  "from",
  "by",
  "at",
  "as",
  "into",
  "about",
  "over",
  "under",
  "again",
  "here",
  "there",
  "when",
  "what",
  "who",
  "how",
  "why",
  "do",
  "does",
  "did",
  "doing",
  "have",
  "has",
  "had",
  "not",
  "going",
  "gonna",
  "wanna",
  "please",
  "like",
  "invest",
  "investing",
  "investment",
  "investments",
  "buy",
  "sell",
  "buying",
  "selling",
  "trade",
  "trading",
  "hold",
  "holding",
  "shit",
  "crap",
  "fuck",
  "fucking",
  "damn",
  "toilet",
  "totally",
  "absolutely",
  "obviously"
]);
function asRecord(value) {
  if (!value || typeof value !== "object" || Array.isArray(value)) return null;
  return value;
}
function asString(value) {
  if (typeof value !== "string") return null;
  const trimmed = value.trim();
  return trimmed ? trimmed : null;
}
function asNumber(value) {
  if (typeof value === "number" && Number.isFinite(value)) return value;
  if (typeof value === "string" && value.trim() && Number.isFinite(Number(value))) return Number(value);
  return null;
}
function parseJsonArray(value) {
  if (Array.isArray(value)) return value;
  if (typeof value !== "string" || !value.trim()) return [];
  try {
    const parsed = JSON.parse(value);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}
function stem(token) {
  if (token.length > 3 && token.endsWith("s")) return token.slice(0, -1);
  return token;
}
function normalizeForTokens(text) {
  return text.replace(new RegExp("(\\p{L})\\.(?=\\p{L})", "gu"), "$1").replace(/(\d),(?=\d)/g, "$1").replace(/[$£€]/g, "").replace(/[^\p{L}\p{N}\s-]/gu, " ").replace(/\s+/g, " ").trim();
}
function significantTokens(text) {
  return normalizeForTokens(text).split(" ").map((token) => token.toLowerCase()).filter((token) => token && !STOP.has(token) && (/\d/.test(token) || token.length > 1)).map(stem);
}
function cleanStatementQuery(statement) {
  const trimmed = statement.replace(/\s+/g, " ").trim();
  if (!trimmed) return "";
  const kept = normalizeForTokens(trimmed).split(" ").filter((token) => {
    const lower = token.toLowerCase();
    if (!lower) return false;
    if (/\d/.test(lower)) return true;
    if (STOP.has(lower)) return false;
    return lower.length > 1;
  });
  const query = kept.join(" ").slice(0, 140).trim();
  if (query.length >= 3) return query;
  return trimmed.slice(0, 140);
}
function parseStatementParam(raw) {
  if (!raw) return null;
  const text = raw.replace(/\s+/g, " ").trim();
  if (text.length < 2 || text.length > 400) return null;
  return text;
}
function polymarketSearchUrl(query) {
  const params = new URLSearchParams({
    q: query,
    limit_per_type: "5",
    search_profiles: "false",
    keep_closed_markets: "0"
  });
  return `${GAMMA_SEARCH}?${params.toString()}`;
}
function polymarketTrendingUrl() {
  const params = new URLSearchParams({
    active: "true",
    closed: "false",
    order: "volume24hr",
    ascending: "false",
    limit: "8"
  });
  return `${GAMMA_EVENTS}?${params.toString()}`;
}
function formatVolumeUsd(volume) {
  if (!Number.isFinite(volume) || volume <= 0) return null;
  const units = [
    { value: 1e9, suffix: "bn" },
    { value: 1e6, suffix: "m" },
    { value: 1e3, suffix: "k" }
  ];
  for (const unit of units) {
    if (volume >= unit.value) {
      const scaled = volume / unit.value;
      const digits = scaled >= 100 ? 0 : 1;
      const text = scaled.toFixed(digits).replace(/\.0$/, "");
      return `$${text}${unit.suffix}`;
    }
  }
  return `$${Math.round(volume)}`;
}
function formatPricePercent(price) {
  const rounded = Math.round(price * 1e3) / 10;
  const text = Number.isInteger(rounded) ? String(rounded) : rounded.toFixed(1);
  return `${text}%`;
}
function eventSlug(value) {
  const slug = asString(value)?.toLowerCase();
  if (!slug || !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) return null;
  return slug;
}
function isClosed(record) {
  return record.closed === true || record.archived === true;
}
function readIsoDate(value) {
  const text = asString(value);
  if (!text) return null;
  const time = Date.parse(text);
  if (!Number.isFinite(time)) return null;
  return new Date(time).toISOString();
}
function overlapScore(query, text) {
  const wanted = new Set(significantTokens(query));
  if (!wanted.size) return 0;
  let score = 0;
  const seen = /* @__PURE__ */ new Set();
  for (const token of significantTokens(text)) {
    if (!wanted.has(token) || seen.has(token)) continue;
    seen.add(token);
    score += 1;
  }
  return score;
}
function readOutcomes(market) {
  const labels = parseJsonArray(market.outcomes).map((item) => asString(item)).filter((item) => Boolean(item));
  const prices = parseJsonArray(market.outcomePrices);
  const pairs = [];
  const count = Math.min(labels.length, prices.length, 4);
  for (let index = 0; index < count; index += 1) {
    const price = asNumber(prices[index]);
    const label = labels[index];
    if (!label || price === null || price < 0 || price > 1) continue;
    pairs.push({ label, price, percentLabel: formatPricePercent(price) });
  }
  return pairs;
}
function marketVolume(market) {
  return asNumber(market.volumeNum) ?? asNumber(market.volume);
}
function rankMarkets(query, markets) {
  if (!Array.isArray(markets)) return null;
  let best = null;
  for (const item of markets) {
    const market = asRecord(item);
    if (!market || isClosed(market) || market.active === false) continue;
    const title = asString(market.question) ?? asString(market.groupItemTitle);
    if (!title) continue;
    const overlap = overlapScore(query, `${title} ${asString(market.groupItemTitle) ?? ""}`);
    const volume = marketVolume(market) ?? 0;
    const ranked = {
      id: asString(market.id) ?? asString(market.slug) ?? title,
      title,
      overlap,
      volume,
      outcomes: readOutcomes(market),
      endDate: readIsoDate(market.endDate)
    };
    if (!best || ranked.overlap > best.overlap || ranked.overlap === best.overlap && ranked.volume > best.volume) {
      best = ranked;
    }
  }
  return best;
}
function selectLiveMatches(payload, query) {
  const root = asRecord(payload);
  const events = root && Array.isArray(root.events) ? root.events : [];
  const matches = [];
  const seen = /* @__PURE__ */ new Set();
  const querySize = new Set(significantTokens(query)).size;
  const minimumOverlap = querySize <= 1 ? 1 : 2;
  for (const item of events) {
    const event = asRecord(item);
    if (!event || isClosed(event) || event.active === false) continue;
    const slug = eventSlug(event.slug);
    if (!slug || seen.has(slug)) continue;
    const eventTitle = asString(event.title) ?? "";
    const best = rankMarkets(query, event.markets);
    if (!best) continue;
    const overlap = Math.max(best.overlap, overlapScore(query, eventTitle));
    if (overlap < minimumOverlap) continue;
    seen.add(slug);
    matches.push({
      id: best.id,
      title: best.title,
      eventTitle,
      url: `${EVENT_URL}/${slug}`,
      outcomes: best.outcomes,
      volumeLabel: formatVolumeUsd(best.volume),
      volumeWindow: best.volume > 0 ? "lifetime" : null,
      origin: "closest",
      endDate: best.endDate ?? readIsoDate(event.endDate)
    });
    if (matches.length >= MAX_MATCHES) break;
  }
  return matches;
}
function pickBusiestMarket(markets) {
  if (!Array.isArray(markets)) return null;
  let best = null;
  for (const item of markets) {
    const market = asRecord(item);
    if (!market || isClosed(market) || market.active === false) continue;
    const title = asString(market.question) ?? asString(market.groupItemTitle);
    if (!title) continue;
    const ranked = {
      id: asString(market.id) ?? asString(market.slug) ?? title,
      title,
      volume24: asNumber(market.volume24hr) ?? 0,
      lifetime: marketVolume(market) ?? 0,
      outcomes: readOutcomes(market),
      endDate: readIsoDate(market.endDate)
    };
    if (!best || ranked.volume24 > best.volume24 || ranked.volume24 === best.volume24 && ranked.lifetime > best.lifetime) {
      best = ranked;
    }
  }
  return best;
}
function selectTrendingMarkets(payload) {
  const root = asRecord(payload);
  const events = Array.isArray(payload) ? payload : root && Array.isArray(root.events) ? root.events : [];
  const matches = [];
  const seen = /* @__PURE__ */ new Set();
  for (const item of events) {
    const event = asRecord(item);
    if (!event || isClosed(event) || event.active === false) continue;
    const slug = eventSlug(event.slug);
    if (!slug || seen.has(slug)) continue;
    const best = pickBusiestMarket(event.markets);
    if (!best) continue;
    seen.add(slug);
    const useDay = best.volume24 > 0;
    const volume = useDay ? best.volume24 : best.lifetime;
    matches.push({
      id: `trend-${best.id}`,
      title: best.title,
      eventTitle: asString(event.title) ?? "",
      url: `${EVENT_URL}/${slug}`,
      outcomes: best.outcomes,
      volumeLabel: formatVolumeUsd(volume),
      volumeWindow: useDay ? "24h" : volume > 0 ? "lifetime" : null,
      origin: "trending",
      endDate: best.endDate ?? readIsoDate(event.endDate)
    });
    if (matches.length >= MAX_TRENDS) break;
  }
  return matches;
}
async function fetchGamma(query, fetchImpl) {
  const response = await fetchImpl(polymarketSearchUrl(query), {
    headers: {
      Accept: "application/json",
      "User-Agent": USER_AGENT
    },
    signal: AbortSignal.timeout(8e3)
  });
  if (!response.ok) {
    throw new Error(`Polymarket search returned ${response.status}`);
  }
  return response.json();
}
async function fetchTrending(fetchImpl) {
  const response = await fetchImpl(polymarketTrendingUrl(), {
    headers: {
      Accept: "application/json",
      "User-Agent": USER_AGENT
    },
    signal: AbortSignal.timeout(8e3)
  });
  if (!response.ok) {
    throw new Error(`Polymarket trends returned ${response.status}`);
  }
  return selectTrendingMarkets(await response.json());
}
async function searchPolymarket(statement, fetchImpl = fetch) {
  const cleaned = cleanStatementQuery(statement);
  const raw = statement.replace(/\s+/g, " ").trim().slice(0, 180);
  const firstQuery = cleaned || raw;
  if (firstQuery.length < 2) return { query: firstQuery, matches: [], trends: [] };
  let query = firstQuery;
  let matches = [];
  let searchError = null;
  try {
    const primary = selectLiveMatches(await fetchGamma(firstQuery, fetchImpl), firstQuery);
    if (primary.length || !raw || raw.toLowerCase() === firstQuery.toLowerCase()) {
      matches = primary;
    } else {
      const secondary = selectLiveMatches(await fetchGamma(raw, fetchImpl), raw);
      if (secondary.length) {
        matches = secondary;
        query = raw;
      }
    }
  } catch (error) {
    searchError = error;
  }
  let trends = [];
  let trendsError = null;
  try {
    trends = await fetchTrending(fetchImpl);
  } catch (error) {
    trendsError = error;
  }
  if (searchError && trendsError) {
    throw searchError;
  }
  return { query, matches, trends };
}

// server/handlers/polymarket.ts
function json(status, body, cache) {
  return Response.json(body, {
    status,
    headers: { "Cache-Control": cache }
  });
}
async function handle(request) {
  if (request.method !== "GET") {
    return json(405, { error: "Method not allowed" }, "no-store");
  }
  const statement = parseStatementParam(new URL(request.url).searchParams.get("q"));
  if (!statement) {
    return json(400, { error: "Pass a statement as q." }, "no-store");
  }
  try {
    const payload = await searchPolymarket(statement);
    return json(200, payload, "public, max-age=60");
  } catch (error) {
    return json(
      502,
      {
        error: "The live market search could not be reached.",
        detail: error instanceof Error ? error.message : "unknown"
      },
      "no-store"
    );
  }
}
function GET(request) {
  return handle(request);
}
var polymarket_default = {
  fetch(request) {
    return handle(request);
  }
};
export {
  GET,
  polymarket_default as default
};
