// Generated by scripts/bundle-api.mjs from server/handlers. Do not edit by hand.

// src/data/fallbackQuotes.ts
var FALLBACK_AS_OF = "2026-09-19T16:00:00.000Z";
var SNAPSHOT = {
  SPY: { price: 761.69, previousClose: 764.29 },
  QQQ: { price: 721.45, previousClose: 714.88 },
  IWM: { price: 284.1, previousClose: 288.89 },
  DIA: { price: 515.88, previousClose: 525.79 },
  EWU: { price: 47.27, previousClose: 47.94 },
  EWG: { price: 42.15, previousClose: 42.87 },
  EWJ: { price: 97, previousClose: 98.56 },
  AAPL: { price: 336.13, previousClose: 332.27 },
  MSFT: { price: 493.78, previousClose: 495.63 },
  GOOGL: { price: 349.54, previousClose: 338.5 },
  AMZN: { price: 253.71, previousClose: 256.78 },
  META: { price: 665.75, previousClose: 648.03 },
  NVDA: { price: 222.27, previousClose: 218.29 },
  TSLA: { price: 364.27, previousClose: 365.44 },
  JPM: { price: 349.67, previousClose: 356.23 },
  XOM: { price: 163.54, previousClose: 165.99 },
  JNJ: { price: 269.99, previousClose: 265.58 },
  V: { price: 368.29, previousClose: 370.45 },
  UNH: { price: 376.9, previousClose: 379.09 },
  GLD: { price: 401.17, previousClose: 398.77 },
  SLV: { price: 59.93, previousClose: 58.12 },
  USO: { price: 153.82, previousClose: 154.9 },
  CPER: { price: 40.23, previousClose: 39.18 },
  IBIT: { price: 46.02, previousClose: 43.77 }
};
var FALLBACK_DELAY_NOTE = "Demo/fallback marks from a stored delayed snapshot \u2014 not a live broker quote. The public feed was unavailable.";
function fallbackQuote(symbolId) {
  const row = SNAPSHOT[symbolId.toUpperCase()];
  if (!row) return void 0;
  return {
    symbolId: symbolId.toUpperCase(),
    price: row.price,
    previousClose: row.previousClose,
    currency: "USD",
    asOf: FALLBACK_AS_OF,
    source: "fallback",
    delayNote: FALLBACK_DELAY_NOTE
  };
}

// src/data/universe.ts
var UNIVERSE = [
  {
    id: "SPY",
    yahooSymbol: "SPY",
    displaySymbol: "SPY",
    name: "S&P 500 (SPDR ETF)",
    assetClass: "index",
    quoteVehicle: "etf-proxy",
    vehicleNote: "Paper marks use SPY, a liquid US-listed ETF, as a proxy for the S&P 500 cash index \u2014 not the index future itself.",
    keywords: ["s&p", "spx", "sp500", "us market", "us equities", "wall street", "spy"],
    region: "US"
  },
  {
    id: "QQQ",
    yahooSymbol: "QQQ",
    displaySymbol: "QQQ",
    name: "Nasdaq-100 (Invesco ETF)",
    assetClass: "index",
    quoteVehicle: "etf-proxy",
    vehicleNote: "Paper marks use QQQ as a liquid proxy for the Nasdaq-100, which is heavier in large US technology names than the S&P 500.",
    keywords: ["nasdaq", "ndx", "qqq", "tech", "growth"],
    region: "US"
  },
  {
    id: "IWM",
    yahooSymbol: "IWM",
    displaySymbol: "IWM",
    name: "Russell 2000 (iShares ETF)",
    assetClass: "index",
    quoteVehicle: "etf-proxy",
    vehicleNote: "Paper marks use IWM as a liquid proxy for the Russell 2000, a gauge of smaller US listed companies.",
    keywords: ["russell", "small cap", "iwm", "small companies"],
    region: "US"
  },
  {
    id: "DIA",
    yahooSymbol: "DIA",
    displaySymbol: "DIA",
    name: "Dow Jones Industrial Average (SPDR ETF)",
    assetClass: "index",
    quoteVehicle: "etf-proxy",
    vehicleNote: "Paper marks use DIA as a liquid proxy for the Dow Jones Industrial Average, a price-weighted basket of 30 large US companies.",
    keywords: ["dow", "djia", "dia", "industrials"],
    region: "US"
  },
  {
    id: "EWU",
    yahooSymbol: "EWU",
    displaySymbol: "EWU",
    name: "UK large caps (iShares MSCI United Kingdom ETF)",
    assetClass: "index",
    quoteVehicle: "etf-proxy",
    vehicleNote: "Paper marks use EWU, a US-listed ETF of large UK companies, as a liquid stand-in for a FTSE-style UK equity view \u2014 not the FTSE 100 future.",
    keywords: ["ftse", "uk", "britain", "london", "ewu"],
    region: "UK"
  },
  {
    id: "EWG",
    yahooSymbol: "EWG",
    displaySymbol: "EWG",
    name: "Germany large caps (iShares MSCI Germany ETF)",
    assetClass: "index",
    quoteVehicle: "etf-proxy",
    vehicleNote: "Paper marks use EWG as a liquid proxy for large German listed companies \u2014 a cousin of a DAX view, not the DAX future.",
    keywords: ["dax", "germany", "frankfurt", "ewg"],
    region: "DE"
  },
  {
    id: "EWJ",
    yahooSymbol: "EWJ",
    displaySymbol: "EWJ",
    name: "Japan large caps (iShares MSCI Japan ETF)",
    assetClass: "index",
    quoteVehicle: "etf-proxy",
    vehicleNote: "Paper marks use EWJ as a liquid proxy for large Japanese listed companies \u2014 a cousin of a Nikkei view, not the Nikkei future.",
    keywords: ["nikkei", "japan", "tokyo", "ewj"],
    region: "JP"
  },
  {
    id: "AAPL",
    yahooSymbol: "AAPL",
    displaySymbol: "AAPL",
    name: "Apple",
    assetClass: "stock",
    quoteVehicle: "stock",
    vehicleNote: "Ordinary US-listed common shares. Paper marks follow the public Apple share price.",
    keywords: ["apple", "iphone", "aapl"],
    region: "US"
  },
  {
    id: "MSFT",
    yahooSymbol: "MSFT",
    displaySymbol: "MSFT",
    name: "Microsoft",
    assetClass: "stock",
    quoteVehicle: "stock",
    vehicleNote: "Ordinary US-listed common shares. Paper marks follow the public Microsoft share price.",
    keywords: ["microsoft", "msft", "azure", "windows"],
    region: "US"
  },
  {
    id: "GOOGL",
    yahooSymbol: "GOOGL",
    displaySymbol: "GOOGL",
    name: "Alphabet",
    assetClass: "stock",
    quoteVehicle: "stock",
    vehicleNote: "Class A US-listed shares. Paper marks follow the public Alphabet share price.",
    keywords: ["google", "alphabet", "googl", "search"],
    region: "US"
  },
  {
    id: "AMZN",
    yahooSymbol: "AMZN",
    displaySymbol: "AMZN",
    name: "Amazon",
    assetClass: "stock",
    quoteVehicle: "stock",
    vehicleNote: "Ordinary US-listed common shares. Paper marks follow the public Amazon share price.",
    keywords: ["amazon", "amzn", "aws"],
    region: "US"
  },
  {
    id: "META",
    yahooSymbol: "META",
    displaySymbol: "META",
    name: "Meta Platforms",
    assetClass: "stock",
    quoteVehicle: "stock",
    vehicleNote: "Ordinary US-listed common shares. Paper marks follow the public Meta share price.",
    keywords: ["meta", "facebook", "instagram"],
    region: "US"
  },
  {
    id: "NVDA",
    yahooSymbol: "NVDA",
    displaySymbol: "NVDA",
    name: "NVIDIA",
    assetClass: "stock",
    quoteVehicle: "stock",
    vehicleNote: "Ordinary US-listed common shares. Paper marks follow the public NVIDIA share price.",
    keywords: ["nvidia", "nvda", "gpu", "ai chips"],
    region: "US"
  },
  {
    id: "TSLA",
    yahooSymbol: "TSLA",
    displaySymbol: "TSLA",
    name: "Tesla",
    assetClass: "stock",
    quoteVehicle: "stock",
    vehicleNote: "Ordinary US-listed common shares. Paper marks follow the public Tesla share price.",
    keywords: ["tesla", "tsla", "ev", "electric car"],
    region: "US"
  },
  {
    id: "JPM",
    yahooSymbol: "JPM",
    displaySymbol: "JPM",
    name: "JPMorgan Chase",
    assetClass: "stock",
    quoteVehicle: "stock",
    vehicleNote: "Ordinary US-listed common shares. Paper marks follow the public JPMorgan share price.",
    keywords: ["jpmorgan", "jpm", "bank", "banks"],
    region: "US"
  },
  {
    id: "XOM",
    yahooSymbol: "XOM",
    displaySymbol: "XOM",
    name: "Exxon Mobil",
    assetClass: "stock",
    quoteVehicle: "stock",
    vehicleNote: "Ordinary US-listed common shares. Paper marks follow the public Exxon Mobil share price.",
    keywords: ["exxon", "xom", "oil major", "energy stock"],
    region: "US"
  },
  {
    id: "JNJ",
    yahooSymbol: "JNJ",
    displaySymbol: "JNJ",
    name: "Johnson & Johnson",
    assetClass: "stock",
    quoteVehicle: "stock",
    vehicleNote: "Ordinary US-listed common shares. Paper marks follow the public Johnson & Johnson share price.",
    keywords: ["johnson", "jnj", "healthcare"],
    region: "US"
  },
  {
    id: "V",
    yahooSymbol: "V",
    displaySymbol: "V",
    name: "Visa",
    assetClass: "stock",
    quoteVehicle: "stock",
    vehicleNote: "Ordinary US-listed common shares. Paper marks follow the public Visa share price.",
    keywords: ["visa", "payments"],
    region: "US"
  },
  {
    id: "UNH",
    yahooSymbol: "UNH",
    displaySymbol: "UNH",
    name: "UnitedHealth",
    assetClass: "stock",
    quoteVehicle: "stock",
    vehicleNote: "Ordinary US-listed common shares. Paper marks follow the public UnitedHealth share price.",
    keywords: ["unitedhealth", "unh", "health insurer"],
    region: "US"
  },
  {
    id: "GLD",
    yahooSymbol: "GLD",
    displaySymbol: "GLD",
    name: "Gold (SPDR Gold Shares)",
    assetClass: "commodity",
    quoteVehicle: "etf-proxy",
    vehicleNote: "Paper marks use GLD, a liquid ETF backed by allocated gold, as a proxy for a gold view \u2014 not a COMEX gold future.",
    keywords: ["gold", "gld", "bullion", "precious metal"]
  },
  {
    id: "SLV",
    yahooSymbol: "SLV",
    displaySymbol: "SLV",
    name: "Silver (iShares Silver Trust)",
    assetClass: "commodity",
    quoteVehicle: "etf-proxy",
    vehicleNote: "Paper marks use SLV, a liquid silver ETF, as a proxy for a silver view \u2014 not a silver future.",
    keywords: ["silver", "slv"]
  },
  {
    id: "USO",
    yahooSymbol: "USO",
    displaySymbol: "USO",
    name: "WTI crude oil (United States Oil Fund)",
    assetClass: "commodity",
    quoteVehicle: "etf-proxy",
    vehicleNote: "Paper marks use USO, a liquid ETF that holds WTI crude futures, as a proxy for an oil view \u2014 not a single continuous futures contract you can roll yourself.",
    keywords: ["oil", "wti", "crude", "uso", "petroleum"]
  },
  {
    id: "CPER",
    yahooSymbol: "CPER",
    displaySymbol: "CPER",
    name: "Copper (United States Copper Index Fund)",
    assetClass: "commodity",
    quoteVehicle: "etf-proxy",
    vehicleNote: "Paper marks use CPER, a liquid ETF linked to copper futures, as a proxy for a copper view \u2014 not the COMEX copper future itself.",
    keywords: ["copper", "cper", "industrial metal", "dr copper"]
  },
  {
    id: "IBIT",
    yahooSymbol: "IBIT",
    displaySymbol: "IBIT",
    name: "Spot Bitcoin (iShares Bitcoin Trust)",
    assetClass: "crypto",
    quoteVehicle: "etf-proxy",
    vehicleNote: "Paper marks use IBIT, a US-listed spot Bitcoin product, as a liquid proxy for a Bitcoin view \u2014 not a wallet of coins and not a futures contract.",
    keywords: ["bitcoin", "btc", "crypto", "ibit"]
  }
];
var UNIVERSE_BY_ID = Object.fromEntries(UNIVERSE.map((item) => [item.id, item]));
function getSymbol(id) {
  return UNIVERSE_BY_ID[id.toUpperCase()];
}

// src/lib/markets/providers/yahoo.ts
var LIVE_DELAY_NOTE = "Public delayed mark via Yahoo Finance chart data \u2014 not a broker quote, and not an executable price.";
function parseYahooChart(payload, symbolId) {
  const body = payload;
  const meta = body.chart?.result?.[0]?.meta;
  const price = meta?.regularMarketPrice;
  if (!meta || !Number.isFinite(price) || (price ?? 0) <= 0) return null;
  const previous = meta.chartPreviousClose ?? meta.previousClose;
  const asOf = meta.regularMarketTime ? new Date(meta.regularMarketTime * 1e3).toISOString() : (/* @__PURE__ */ new Date()).toISOString();
  return {
    symbolId,
    price,
    previousClose: Number.isFinite(previous) ? previous : void 0,
    currency: meta.currency ?? "USD",
    asOf,
    source: "live-delayed",
    delayNote: LIVE_DELAY_NOTE
  };
}
async function fetchYahooQuote(yahooSymbol, symbolId = yahooSymbol, fetchImpl = fetch) {
  const url = `https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(
    yahooSymbol
  )}?interval=1d&range=5d`;
  const response = await fetchImpl(url, {
    headers: {
      "User-Agent": "WeAlmostAgreePaper/0.2 (educational simulator; delayed public marks)",
      Accept: "application/json"
    }
  });
  if (!response.ok) return null;
  const payload = await response.json();
  return parseYahooChart(payload, symbolId);
}
async function fetchYahooQuotes(symbols, fetchImpl = fetch) {
  const unique = /* @__PURE__ */ new Map();
  for (const symbol of symbols) {
    unique.set(symbol.id, symbol);
  }
  const results = await Promise.all(
    [...unique.values()].map(async (symbol) => {
      try {
        return await fetchYahooQuote(symbol.yahooSymbol, symbol.id, fetchImpl);
      } catch {
        return null;
      }
    })
  );
  return results.filter((quote) => Boolean(quote));
}

// src/lib/markets/quoteApi.ts
var MAX_QUOTE_SYMBOLS = 24;
function parseSymbolQuery(raw) {
  if (!raw) return [];
  const ids = raw.split(",").map((part) => part.trim().toUpperCase()).filter(Boolean);
  return [...new Set(ids)].slice(0, MAX_QUOTE_SYMBOLS);
}
async function buildQuotePayload(symbolIds, fetchImpl = fetch) {
  const known = symbolIds.map((id) => getSymbol(id)).filter((item) => Boolean(item));
  const live = known.length ? await fetchYahooQuotes(
    known.map((item) => ({ id: item.id, yahooSymbol: item.yahooSymbol })),
    fetchImpl
  ) : [];
  const liveById = Object.fromEntries(live.map((quote) => [quote.symbolId, quote]));
  const quotes = [];
  const missing = [];
  let fallbackUsed = false;
  for (const id of symbolIds) {
    const liveQuote = liveById[id];
    if (liveQuote) {
      quotes.push(liveQuote);
      continue;
    }
    const fallback = fallbackQuote(id);
    if (fallback) {
      quotes.push(fallback);
      fallbackUsed = true;
      continue;
    }
    missing.push(id);
  }
  const asOf = quotes[0]?.asOf ?? (/* @__PURE__ */ new Date()).toISOString();
  return { quotes, missing, fallbackUsed, asOf };
}

// server/handlers/quote.ts
function json(status, body, cache) {
  return Response.json(body, {
    status,
    headers: { "Cache-Control": cache }
  });
}
async function handle(request) {
  if (request.method !== "GET") {
    return json(405, { error: "Method not allowed" }, "no-store");
  }
  const symbols = parseSymbolQuery(new URL(request.url).searchParams.get("symbols"));
  if (!symbols.length) {
    return json(400, { error: "Pass symbols as a comma-separated list, e.g. ?symbols=SPY,GLD" }, "no-store");
  }
  try {
    const payload = await buildQuotePayload(symbols);
    return json(200, payload, "public, max-age=30");
  } catch (error) {
    return json(
      502,
      {
        error: "The public price feed could not be reached.",
        detail: error instanceof Error ? error.message : "unknown"
      },
      "no-store"
    );
  }
}
function GET(request) {
  return handle(request);
}
var quote_default = {
  fetch(request) {
    return handle(request);
  }
};
export {
  GET,
  quote_default as default
};
